# Add monitors for the reward node to handle dispensing conditions below
/reward:
  ros__parameters:
    state_topic: '/machine/state'
    device:
      port: '/dev/ttyACM0'
      baudrate: 115200
    use_sim_time: false
    test_param: true
    state_monitor:
      enable: true
      target_a:
        hold_time: 1    
        dispense_time: 0
        repeat: 1
      target_b:
        hold_time: 200
        dispense_time:  500
        repeat: 1
      target_c:
        hold_time: 200
        dispense_time: 700
        repeat: 1
    velocity_monitor:
      enable: false
      threshold: 0.5
      dispense_time: 700

